### ISSUE TITLE
react application

### ISSUE THREAD

**Issue by agserrano3** [agserrano3/test_repo#116]
Create a very basic react application with one unique main page that displays the current time of the user

**Comment by Yassin-Aru** [comment]
U can also use this:

`const TimeDisplay = () => {
    const [time, setTime] = useState(new Date().toLocaleTimeString());

    setInterval(() => {
        setTime(new Date().toLocaleTimeString());
    }, 1000);

    return (
        <div>
            <h1>Current Time</h1>
            <p>{time}</p>
        </div>
    );
}`
